name: DP-Shop
version: 1.0.1.7
main: com.darksoldier1404.dps.Shop
authors: [ DEAD_POOLIO_ ]
api-version: 1.14
depend:
  - DPP-Core
  - Essentials
  - PlaceholderAPI
commands:
  dshop:
    aliases: [ dpshop, dps ]
